/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_ngame_store_ota_model_OtaService_OtcBinder */

#ifndef _Included_cn_ngame_store_ota_model_OtaService_OtcBinder
#define _Included_cn_ngame_store_ota_model_OtaService_OtcBinder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
