/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_ngame_store_ota_model_OtaService_MyBluetoothGattCallback */

#ifndef _Included_cn_ngame_store_ota_model_OtaService_MyBluetoothGattCallback
#define _Included_cn_ngame_store_ota_model_OtaService_MyBluetoothGattCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
